----------------------------------------------------------------------------
--  Lab 1: DDS and the Audio Codec
----------------------------------------------------------------------------
--  ENGS 128
--  Author: Kendall Farnham
----------------------------------------------------------------------------
--  Description: DDS Controller with Block Memory (BROM) for storing samples
--
--  Architecture:
--    phase_inc_i ──► phase accumulator (PHASE_DATA_WIDTH bits, wraps on overflow)
--                         │
--                         ▼ (address)
--                       BRAM sine LUT (2^PHASE_DATA_WIDTH entries × DDS_DATA_WIDTH bits)
--                         │
--                         ▼
--                       data_o (1 cycle BRAM read latency)
--
--  Phase increment calculation (48 kHz sampling rate):
--    phase_inc = round( f_desired × 2^PHASE_DATA_WIDTH / Fs )
--              = round( f_desired × 4096 / 48000 )
--
--  BRAM IP setup (Vivado Block Memory Generator):
--    - Component name  : sine_lut
--    - Memory type     : Single Port ROM
--    - Width           : 24 bits  (DDS_DATA_WIDTH)
--    - Depth           : 4096     (2^PHASE_DATA_WIDTH)
--    - Read latency    : 1 cycle  (default)
--    - COE file        : sine_lut.coe  (generated in MATLAB, signed decimal)
--
--  MATLAB COE generation (run once, commit sine_lut.coe to repo):
--    N = 4096; bits = 24; A = 2^(bits-1) - 1;
--    samples = round(A * sin(2*pi*(0:N-1)/N));
--    % write memory_initialization_radix=10 COE file
----------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use ieee.math_real.all;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

----------------------------------------------------------------------------
-- Entity definition
----------------------------------------------------------------------------
entity dds_controller is
    Generic (
        DDS_DATA_WIDTH   : integer := 24;   -- sine sample width (bits)
        PHASE_DATA_WIDTH : integer := 12);  -- phase accumulator width (bits)
                                            -- → 2^12 = 4096 LUT entries
    Port (
        clk_i       : in  std_logic;                                     -- 48 kHz sample clock
        enable_i    : in  std_logic;                                     -- increment phase when high
        reset_i     : in  std_logic;                                     -- synchronous reset (takes priority)
        phase_inc_i : in  std_logic_vector(PHASE_DATA_WIDTH-1 downto 0); -- frequency select
        data_o      : out std_logic_vector(DDS_DATA_WIDTH-1 downto 0));  -- sine sample out
end dds_controller;

----------------------------------------------------------------------------
architecture Behavioral of dds_controller is
----------------------------------------------------------------------------

----------------------------------------------------------------------------
-- Phase accumulator
-- Unsigned, wraps naturally on overflow (no explicit modulo needed)
----------------------------------------------------------------------------
signal phase_acc : unsigned(PHASE_DATA_WIDTH-1 downto 0) := (others => '0');

----------------------------------------------------------------------------
-- BRAM sine LUT component
-- Generated by Vivado Block Memory Generator IP, named "sine_lut"
-- Single Port ROM: 4096 × 24-bit, 1-cycle read latency
----------------------------------------------------------------------------
component sine_lut is
    Port (
        clka  : in  std_logic;
        ena   : in  std_logic;
        addra : in  std_logic_vector(PHASE_DATA_WIDTH-1 downto 0);
        douta : out std_logic_vector(DDS_DATA_WIDTH-1 downto 0));
end component;

----------------------------------------------------------------------------
begin
----------------------------------------------------------------------------

----------------------------------------------------------------------------
-- Phase accumulator process
-- reset_i takes priority over enable_i
-- Phase wraps automatically on unsigned overflow (free modulo 2^PHASE_DATA_WIDTH)
----------------------------------------------------------------------------
phase_accum : process(clk_i)
begin
    if rising_edge(clk_i) then
        if reset_i = '1' then
            phase_acc <= (others => '0');
        elsif enable_i = '1' then
            phase_acc <= phase_acc + unsigned(phase_inc_i);
        end if;
    end if;
end process phase_accum;

----------------------------------------------------------------------------
-- BRAM sine LUT instantiation
-- Address driven by phase accumulator — output lags by 1 clock cycle (BRAM latency)
-- ena tied high: BRAM always enabled, phase accumulator controls the address
----------------------------------------------------------------------------
bram_sine_lut : sine_lut
    port map (
        clka  => clk_i,
        ena   => '1',
        addra => std_logic_vector(phase_acc),
        douta => data_o);

----------------------------------------------------------------------------
end Behavioral;
